
services:

  db:
    image: postgres:15
    container_name: automation-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    env_file:
      - .env

  web:
    build: .
    container_name: hotel-api
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
