# Generated by Django 5.2.4 on 2025-07-29 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('token', models.CharField(blank=True, editable=False, max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('api_token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('api_address', models.CharField(blank=True, max_length=255)),
                ('observation', models.TextField(blank=True)),
                ('installation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.state')),
            ],
        ),
    ]
