# Generated by Django 5.2.4 on 2025-09-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_token',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
