# Generated by Django 5.2.4 on 2025-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_api_token_alter_client_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='information_basic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prompt_ai',
            field=models.TextField(blank=True),
        ),
    ]
