# Generated by Django 5.2.4 on 2025-07-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_chat_id_chat_contact_id_message'),
        ('common', '0002_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='common.origin'),
        ),
        migrations.AddField(
            model_name='message',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='common.origin'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact_id',
            field=models.CharField(help_text='Sender of message, e.g., phone number or username', max_length=255),
        ),
    ]
