# Generated by Django 5.2.4 on 2025-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_message_sender_chat_origin_message_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(default=0, help_text='Unique identifier for the chat', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
