# Generated by Django 5.2.4 on 2025-08-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
    ]
