# Generated by Django 5.2.4 on 2025-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_chat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='contact_id',
            field=models.CharField(max_length=255),
        ),
    ]
