# Generated by Django 5.2.4 on 2025-08-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chat_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='flow',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if the chat is part of a flow', null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='flow_option',
            field=models.IntegerField(blank=True, default=0, help_text='Option selected in the flow, if applicable', null=True),
        ),
    ]
