# Generated by Django 5.2.4 on 2025-08-10 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chat_flow_alter_chat_flow_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages_chat_id', to='chats.chat'),
            preserve_default=False,
        ),
    ]
