# Generated by Django 5.2.4 on 2025-08-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_message_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
