# Generated by Django 5.2.4 on 2025-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_rename_chat_id_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_availability',
            field=models.BooleanField(default=False, help_text='Indicates if there is room availability'),
        ),
    ]
