# Generated by Django 5.2.4 on 2025-08-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_chat_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, help_text='Number of rooms available or booked', null=True),
        ),
    ]
