# Generated by Django 5.2.4 on 2025-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_chat_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='language',
            field=models.CharField(blank=True, default='unknow', help_text='Language preference for the chat', max_length=20, null=True),
        ),
    ]
