# Generated by Django 5.2.4 on 2025-07-30 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, help_text='Origin of the log integration', max_length=255, null=True)),
                ('to', models.CharField(blank=True, help_text='Destination of the log integration', max_length=255, null=True)),
                ('content', models.TextField(help_text='Content of the log integration')),
                ('response', models.TextField(help_text='Response from the log integration')),
                ('status_http', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_integrations', to='clients.client')),
            ],
        ),
    ]
