# Generated by Django 5.2.4 on 2025-07-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintegration',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Response time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='logintegration',
            name='content',
            field=models.JSONField(help_text='Content of the log integration'),
        ),
        migrations.AlterField(
            model_name='logintegration',
            name='response',
            field=models.JSONField(help_text='Response from the log integration'),
        ),
    ]
