# Generated by Django 5.2.4 on 2025-09-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_hotelrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='number_of_pax',
            field=models.IntegerField(blank=True, default=None, help_text='Number of pax allowed in the room', null=True),
        ),
        migrations.AddField(
            model_name='logintegration',
            name='contact_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
