# Generated by Django 5.2.4 on 2025-11-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_information_basic_client_prompt_ai'),
        ('systems', '0004_hotelrooms_number_of_pax_logintegration_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogApiSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, help_text='Origin of the received JSON', max_length=255, null=True)),
                ('content', models.JSONField(help_text='Content of the received JSON')),
                ('status_message', models.CharField(blank=True, help_text='Status or specific error message of the processing attempt', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_received_jsons', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome identificador do prompt', max_length=100)),
                ('prompt_text', models.TextField(help_text='Texto do prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='clients.client')),
            ],
            options={
                'db_table': 'system_prompts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('quartos', 'Informações sobre Quartos'), ('horarios', 'Horários e Check-in/out'), ('pagamento', 'Formas de Pagamento'), ('servicos', 'Serviços e Amenidades'), ('contato', 'Telefones e Contato'), ('politicas', 'Políticas do Hotel'), ('fluxo_reserva', 'Instruções de Reserva')], max_length=50)),
                ('content', models.TextField(help_text='Conteúdo estruturado em texto')),
                ('keywords', models.JSONField(default=list, help_text='Lista de palavras-chave para busca rápida')),
                ('priority', models.IntegerField(default=0, help_text='Maior = mais importante')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='clients.client')),
            ],
            options={
                'db_table': 'context_categories',
                'ordering': ['-priority', 'category'],
                'unique_together': {('client', 'category')},
            },
        ),
    ]
