# Generated by Django 5.2.4 on 2025-11-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_information_basic_client_prompt_ai'),
        ('systems', '0005_logapisystem_systemprompt_contextcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextcategory',
            options={'ordering': ['-priority', 'category'], 'verbose_name': 'Contexto RAG', 'verbose_name_plural': 'Contextos RAG'},
        ),
        migrations.AlterModelOptions(
            name='systemprompt',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Prompt do Sistema', 'verbose_name_plural': 'Prompts do Sistema'},
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='category',
            field=models.CharField(choices=[('quartos', 'Informações sobre Quartos'), ('horarios', 'Horários e Check-in/out'), ('pagamento', 'Formas de Pagamento'), ('servicos', 'Serviços e Amenidades'), ('contato', 'Telefones e Contato'), ('politicas', 'Políticas do Hotel'), ('fluxo_reserva', 'Instruções de Reserva')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='content',
            field=models.TextField(help_text='Conteúdo que será enviado ao ChatGPT quando este contexto for relevante', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text="Palavras-chave para busca (ex: ['quarto', 'cama', 'reserva'])", verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='priority',
            field=models.IntegerField(default=0, help_text='Maior = mais importante. Contextos com prioridade maior aparecem primeiro.', verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='contextcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Apenas um prompt com o mesmo nome pode estar ativo por vez', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='name',
            field=models.CharField(help_text="Nome identificador (ex: 'main', 'concierge', 'support')", max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='prompt_text',
            field=models.TextField(help_text='Use {chat_id}, {now}, {language} e {context} como placeholders', verbose_name='Texto do Prompt'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Versão'),
        ),
    ]
